constructionapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import( 
    LoginView, 
    LogoutView, 
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

)
from attandance.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attandance.urls')),
    path('officeuser/', include('officeuser.urls')),
    path('siteuser/', include('sitelogin.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

officeuser/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'officeuser'

urlpatterns = [
    path('officeuserlist/', OfficeUserListView.as_view(), name='officeuserlistview'),
    path('officeusercreate/', OfficeUserCreateView.as_view(), name='officeusercreate'),
]

sitelogin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'sitelogin'

urlpatterns = [
    path('siteuserlist/', SiteUserListView.as_view(), name='siteuserlistview'),
    path('siteusercreate/', SiteUserCreateView.as_view(), name='siteusercreate'),
]

officeuser/models.py
from django.db import models

# Create your models here.

officeuser/forms.py
from django import forms
from attandance.models import OfficeLogin
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class OfficeUserModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField() 

officeuser/views.py
from django.shortcuts import render, reverse
from django.views.generic import ListView, UpdateView, DeleteView, DetailView, TemplateView, CreateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from attandance.models import OfficeLogin
from .forms import OfficeUserModelForm
from django.core.mail import send_mail


# Create your views here.
class OfficeUserListView(LoginRequiredMixin, ListView):
    template_name = "officeuserlist.html"
    
      # Set the model for the ListView

    def get_queryset(self):
        return OfficeLogin.objects.all()

class OfficeUserCreateView(LoginRequiredMixin, CreateView):
    template_name = 'officeusercreate.html'
    form_class = OfficeUserModelForm

    def get_success_url(self):
        return reverse("officeuser:officeuserlistview")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_office_login = True
        user.is_admin = False
        user.is_site_engineer = False
        user.save()

        name = form.cleaned_data['name']
        email = form.cleaned_data['email']
        phone = form.cleaned_data['phone']

        # Create a SalesLogin instance or any relevant model
        office_login = OfficeLogin.objects.create(
            user=user,
            name=name,
            email=email,
            phone=phone
        )
        # Send an email
        send_mail(
            subject="You are invited to be a office User",
            message="You were added as a office User On Vivin Contracting and Engineering  LLP. Please Login to the website to start working",
            from_email="theonesolutionmysore@gmail.com",
            recipient_list=[user.email]
        )

        return super(OfficeUserCreateView, self).form_valid(form)

# class OfficeUserUpdateView(LoginRequiredMixin, UpdateView):
#     template_name = 'officeuserupdate.html'
#     form_class = OfficeUserModelForm
    
#     def get_success_url(self):
#         return reverse("officeuser:officeuserlistview")

#     def get_queryset(self):
#         return OfficeLogin.objects.all()

# class SaleUserDeleteView(LoginRequiredMixin, DeleteView):
#     template_name = 'officeuserdelete.html'
#     context_object_name = 'officeuserdelete'
    
#     def get_success_url(self):
#         return reverse("officeuser:officeuserlistview")

#     def get_queryset(self):
#         return OfficeLogin.objects.all()

officeuser/templates/officeusercreate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Office User</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
     <nav>
        <div class="menu" >
            <img src="{% static 'icons/hamburger menu.svg' %}" alt="" onclick="toggleNavigation()">
        </div>
        <ul>
            <li>
                <a href="">Profile</a>
                <img src="{% static 'icons/dropdownarrowsvg.svg' %}" alt="">
            </li>  
        </ul>
    </nav>
    <div class="contentholder">
        <div class="navigation">
            
            <img class="logo" src="{% static 'icons/Vivin-construction-and-engineering-logo.png' %}" alt="">
            <div class="tabholder">
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                </div>
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'projects' %}">Project</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'attendance_recordlist' %}">Attendance</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'overtimelist' %}">Overtime</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'indentlist' %}">Indents</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'contractorslist' %}">Contractor</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'labortypelist' %}">Labor Types</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materialcategorylist' %}">Material Categories</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materiallist' %}">Material List</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'allreports' %}">Ledgers</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="">Users</a>
                </div>
            </div>
        </div>
        <div class="displayboard">
            <div class="whiteboard">
                <div class="alignmentmaker">
                    <h3>Create Sale User</h3>
                    <form  method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" value="save">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/navigation.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>













   
</body>
</html>

officeuser/templates/officeuserlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
    {% if request.user.is_admin %}
     <nav>
        <div class="menu" >
            <img src="{% static 'icons/hamburger menu.svg' %}" alt="" onclick="toggleNavigation()">
        </div>
        <ul>
            <li>
                {% if request.user.is_authenticated %}
                <a href="">{{ request.user.username }}</a>
                <a href="{% url 'logout' %}">Log Out</a> 
                {% else %}
                <a href="">Profile</a>
                <img src="{% static 'icons/dropdownarrowsvg.svg' %}" alt="">
                {% endif %}
            </li>  
        </ul>
    </nav>
    <div class="contentholder">
        <div class="navigation">
            
            <img class="logo" src="{% static 'icons/Vivin-construction-and-engineering-logo.png' %}" alt="">
            <div class="tabholder">
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                </div>
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'projects' %}">Project</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'attendance_recordlist' %}">Attendance</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'overtimelist' %}">Overtime</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'indentlist' %}">Indents</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'contractorslist' %}">Contractor</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'labortypelist' %}">Labor Types</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materialcategorylist' %}">Material Categories</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materiallist' %}">Material List</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'allreports' %}">Ledgers</a>
                </div>
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="">Users</a>
                </div>
            </div>
        </div>
        <div class="displayboard">
            <div class="whiteboard">
                <div class="alignmentmaker">
                    <h3>Office User List</h3>
                    <!-- <div class="boxholder">
                        <div class="dash-card">
                            <div class="heading">
                                <h3>Total Customers</h3>
                            </div>
                        </div>
                    </div> -->
                    {% if request.user.is_admin %}
                    <div class="bottonholder">
                        <a href="{% url 'officeuser:officeusercreate' %}"><button>Add Office User</button></a>
                    </div>
                    {% endif %}
                    <table>
                        <thead>
                            <tr>
                                <th>Username</th>
                                <th>First Name</th>
                                <th>Email</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for saleuser in object_list %}
                            <tr>
                                <td>{{ saleuser.user.username }}</td>
                                <td>{{ saleuser.user.first_name }}</td>
                                <td>{{ saleuser.user.email }}</td>
                                <td class="action">
                                    <a id="view" href=""><div class="buttonview">View</div></a>
                                    <a id="update" href=""><div class="button">Update</div></a>
                                    <a id="delete" href=""><div class="buttondelete">Delete</div></a> 
                                </td>
                            </tr>
                            
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    {% else %}

    <p>Return to Login Page</p>

    {% endif %}
    
    <script src="{% static 'js/navigation.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>
    











   
</body>
</html>