constructionapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import( 
    LoginView, 
    LogoutView, 
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView

)
from attandance.views import SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attandance.urls')),
    path('officeuser/', include('officeuser.urls')),
    path('siteuser/', include('sitelogin.urls')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

sitelogin/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'sitelogin'

urlpatterns = [
    path('siteuserlist/', SiteUserListView.as_view(), name='siteuserlistview'),
    path('siteusercreate/', SiteUserCreateView.as_view(), name='siteusercreate'),
]

attandance/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField
from .models import *
from django.forms import formset_factory
from django_measurement.forms import MeasurementField
from measurement.measures import Area

User = get_user_model()

class CreateCustomUser(UserCreationForm):
    class Meta:
        model = User
        fields = {"username",}
        field_classes = {'username': UsernameField}

class ProjectCreationForm(forms.ModelForm):
    Length = MeasurementField(measurement=Area, unit_choices=[('sq_ft', 'Feet')])
    Breadth = MeasurementField(measurement=Area, unit_choices=[('sq_ft', 'Feet')])

    class Meta:
        model = Project
        fields = (
            'Project_name',
            'Project_location',
            'Project_Start_date',
            'Project_End_date',
            'Floors',
            'Builtup_area',
            'Length',
            'Breadth',
            'Project_Dimensions',
            'site_engineers',
        )
        widgets = {
            'Project_Start_date': forms.DateInput(attrs={'type': 'date'}),
            'Project_End_date': forms.DateInput(attrs={'type': 'date'}),
        }

class AttendanceRecordForm(forms.ModelForm):
    class Meta:
        model = AttendanceRecord
        fields = ['project', 'contractor', 'labor_type', 'number_of_workers', 'Remarks']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)  # Retrieve the user argument and remove it from kwargs
        super().__init__(*args, **kwargs)

        # If user is provided, filter the project's queryset based on the user's role
        if user is not None:
            if user.is_admin or user.is_office_login:
                self.fields['project'].queryset = Project.objects.all()
            elif user.is_site_engineer:
                self.fields['project'].queryset = user.siteengineer.projects.all()
            else:
                self.fields['project'].queryset = Project.objects.none()

        # The rest of your __init__ remains unchanged
        self.fields['contractor'].queryset = Contractor.objects.none()
        self.fields['labor_type'].queryset = LaborTypes.objects.none()

        if 'project' in self.data:
            try:
                project_id = int(self.data.get('project'))
                self.fields['contractor'].queryset = Contractor.objects.filter(Project_id=project_id).order_by('Contractor_name')
                if 'contractor' in self.data:
                    contractor_id = int(self.data.get('contractor'))
                    self.fields['labor_type'].queryset = LaborTypes.objects.filter(Contractor_id=contractor_id).order_by('Labor_type')
            except (ValueError, TypeError):
                pass  # In case of ValueError or TypeError, do not set any queryset
        elif self.instance.pk:
            self.fields['contractor'].queryset = self.instance.project.contractor_set.order_by('Contractor_name')
            self.fields['labor_type'].queryset = self.instance.contractor.labortypes_set.order_by('Labor_type')




class WageCalculationForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    contractor = forms.ModelChoiceField(queryset=Contractor.objects.none())  # Initially empty
    from_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    to_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    def __init__(self, *args, **kwargs):
        super(WageCalculationForm, self).__init__(*args, **kwargs)
        if 'project' in self.data:
            try:
                project_id = int(self.data.get('project'))
                self.fields['contractor'].queryset = Contractor.objects.filter(Project_id=project_id).order_by('Contractor_name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Contractor queryset

class OvertimeWageCalculationForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    contractor = forms.ModelChoiceField(queryset=Contractor.objects.none())  # Initially empty
    from_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    to_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))

    def __init__(self, *args, **kwargs):
        super(OvertimeWageCalculationForm, self).__init__(*args, **kwargs)
        self.fields['contractor'].queryset = Contractor.objects.none()

        if 'project' in self.data:
            try:
                project_id = int(self.data.get('project'))
                self.fields['contractor'].queryset = Contractor.objects.filter(Project_id=project_id)
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty Contractor queryset

class ContractorForm(forms.ModelForm):
    class Meta:
        model = Contractor
        fields = (
            'Contractor_name',
            'Project'
        )

class LaborTypeForm(forms.ModelForm):
    class Meta:
        model = LaborTypes
        fields = ['Contractor', 'Labor_type', 'wage', 'overtime_wage']

class OvertimeRecordForm(forms.ModelForm):
    class Meta:
        model = OvertimeRecord
        fields = ['project', 'contractor', 'labor_type', 'number_of_workers', 'number_of_hours', 'Remarks']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        if user is not None:
            if user.is_admin or user.is_office_login:
                self.fields['project'].queryset = Project.objects.all()
            elif user.is_site_engineer:
                self.fields['project'].queryset = user.siteengineer.projects.all()
            else:
                self.fields['project'].queryset = Project.objects.none()



        self.fields['contractor'].queryset = Contractor.objects.none()
        self.fields['labor_type'].queryset = LaborTypes.objects.none()

        if 'project' in self.data:
            try:
                project_id = int(self.data.get('project'))
                self.fields['contractor'].queryset = Contractor.objects.filter(Project=project_id).order_by('Contractor_name')
                if 'contractor' in self.data:
                    contractor_id = int(self.data.get('contractor'))
                    self.fields['labor_type'].queryset = LaborTypes.objects.filter(Contractor=contractor_id).order_by('Labor_type')
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['contractor'].queryset = self.instance.project.contractor_set.order_by('Contractor_name')
            self.fields['labor_type'].queryset = self.instance.contractor.labortypes_set.order_by('Labor_type')

class MaterialCategoryForm(forms.ModelForm):
    class Meta:
        model = MaterialCategory
        fields = (
            'CategoryName',
        )

class MaterialForm(forms.ModelForm):
    class Meta:
        model = Material
        fields= (
            'category',
            'Materialname',
        )

class IndentCreateForm(forms.ModelForm):
    class Meta:
        model = Indent
        fields = ['Project', 'indent_no','CategoryName', 'Material', 'Quantity']


class IndentUpdateForm(forms.ModelForm):
    class Meta:
        model = Indent
        fields = ['Quantity_order_status', 'Quantity_Recieved_status']

    






  

templates/attendance_record_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attendance</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
     <nav>
        <div class="menu" >
            <img src="{% static 'icons/hamburger menu.svg' %}" alt="" onclick="toggleNavigation()">
        </div>
        <ul>
            <li>
                {% if request.user.is_authenticated %}
                <a href="">{{ request.user.username }}</a>
                <a href="{% url 'logout' %}">Log Out</a> 
                {% else %}
                <a href="">Profile</a>
                <img src="{% static 'icons/dropdownarrowsvg.svg' %}" alt="">
                {% endif %}
            </li>  
        </ul>
    </nav>
    <div class="contentholder">
        <div class="navigation">
            
            <img class="logo" src="{% static 'icons/Vivin-construction-and-engineering-logo.png' %}" alt="">
            <div class="tabholder">
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'projects' %}">Project</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'attendance_recordlist' %}">Attendance</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'overtimelist' %}">Overtime</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'indentlist' %}">Indents</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'contractorslist' %}">Contractor</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'labortypelist' %}">Labor Types</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materialcategorylist' %}">Material Categories</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materiallist' %}">Material List</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'allreports' %}">Ledgers</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="">Users</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="displayboard">
            <div class="whiteboard">
                <div class="alignmentmaker">
                    <h3>Attendance</h3>
                    <div class="bottonholder">
                        <a href="{% url 'attendance_record' %}"><button>Add Attendance</button></a>
                    </div>
                    <div class="tableholder">
                        <table>
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Project Name</th>
                                    <th>Project Contractor</th>
                                    <th>Project Labor Type</th>
                                    <th>No of workers</th>
                                    <th>Remarks</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for rlist in recordlist %}
                                <tr>
                                    <td>{{ rlist.date }}</td>
                                    <td>{{ rlist.project }}</td>
                                    <td>{{ rlist.contractor }}</td>
                                    <td>{{ rlist.labor_type }}</td>
                                    <td>{{ rlist.number_of_workers }}</td>
                                    <td>{{ rlist.Remarks  }}</td>
                                    
                                    <td class="action">
                                        <a id="update" href="{% url 'attendance_recordupdate' rlist.pk %}"><div class="button">Update</div></a>
                                        <a id="delete" href="{% url 'attendance_recorddelete' rlist.pk %}"><div class="buttondelete">Delete</div></a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>    
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/navigation.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>













   
</body>
</html>

templates/attendance_record_list_update.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Attendance</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
     <nav>
        <div class="menu" >
            <img src="{% static 'icons/hamburger menu.svg' %}" alt="" onclick="toggleNavigation()">
        </div>
        <ul>
            <li>
                {% if request.user.is_authenticated %}
                <a href="">{{ request.user.username }}</a>
                <a href="{% url 'logout' %}">Log Out</a> 
                {% else %}
                <a href="">Profile</a>
                <img src="{% static 'icons/dropdownarrowsvg.svg' %}" alt="">
                {% endif %}
            </li>  
        </ul>
    </nav>
    <div class="contentholder">
        <div class="navigation">
            
            <img class="logo" src="{% static 'icons/Vivin-construction-and-engineering-logo.png' %}" alt="">
            <div class="tabholder">
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'projects' %}">Project</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'attendance_recordlist' %}">Attendance</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'overtimelist' %}">Overtime</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'indentlist' %}">Indents</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'contractorslist' %}">Contractor</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'labortypelist' %}">Labor Types</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materialcategorylist' %}">Material Categories</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materiallist' %}">Material List</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'allreports' %}">Ledgers</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="">Users</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="displayboard">
            <div class="whiteboard">
                <div class="alignmentmaker">
                    <h3>Update Attendance {{ attendance.project }}  {{ attendance.date }}</h3>
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" value="save">Save Attendance</button>

                    </form>
                    
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/navigation.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>













   
</body>
</html>

templates/overtime_wage_calculation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports - Overtime</title>
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
</head>
<body>
     <nav>
        <div class="menu" >
            <img src="{% static 'icons/hamburger menu.svg' %}" alt="" onclick="toggleNavigation()">
        </div>
        <ul>
            <li>
                {% if request.user.is_authenticated %}
                <a href="">{{ request.user.username }}</a>
                <a href="{% url 'logout' %}">Log Out</a> 
                {% else %}
                <a href="">Profile</a>
                <img src="{% static 'icons/dropdownarrowsvg.svg' %}" alt="">
                {% endif %}
            </li>  
        </ul>
    </nav>
    <div class="contentholder">
        <div class="navigation">
            
            <img class="logo" src="{% static 'icons/Vivin-construction-and-engineering-logo.png' %}" alt="">
            <div class="tabholder">
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab"  onclick="toggleActive(this)">
                    <a href="{% url 'projects' %}">Project</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'attendance_recordlist' %}">Attendance</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'overtimelist' %}">Overtime</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login or request.user.is_site_engineer %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'indentlist' %}">Indents</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'contractorslist' %}">Contractor</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'labortypelist' %}">Labor Types</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materialcategorylist' %}">Material Categories</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'materiallist' %}">Material List</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="{% url 'allreports' %}">Ledgers</a>
                </div>
                {% endif %}
                {% if request.user.is_admin or request.user.is_office_login %}
                <div class="nav-tab" onclick="toggleActive(this)">
                    <a href="">Users</a>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="displayboard">
            <div class="whiteboard">
                <div class="alignmentmaker">
                    <h3>Overtime Report</h3>
                    <form method="post" id="overtimeWageForm">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" name="show_results">Show Results</button>
                        <button type="submit" name="download_excel">Download as Excel</button>
                    </form>
                    
                    <div class="tableholder">
                        {% if overtime_data %}
                            <h2>Overtime Wage Report</h2>
                            <h3>Project: {{ project.Project_name }}</h3>
                            <h4>Contractor: {{ contractor.Contractor_name }}</h4>
                            <h5>Period: {{ from_date }} to {{ to_date }}</h5>
                            <table>
                                <thead>
                                <tr>
                                    <th>Labor Type</th>
                                    <th>Overtime Wage per Hour</th>
                                    <th>Total Hours</th>
                                    <th>Total Workers</th>
                                    <th>Total Overtime Wage</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for item in overtime_data %}
                                    <tr>
                                    <td>{{ item.labor_type }}</td>
                                    <td>{{ item.overtime_wage }}</td>
                                    <td>{{ item.total_hours }}</td>
                                    <td>{{ item.total_workers }}</td>
                                    <td>{{ item.total_overtime_wage }}</td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>Total Overtime Wage:</th>
                                    <th>{{ total_wage }}</th>
                                </tr>
                                </tfoot>
                            </table>
                            {% endif %}
                    </div>    
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/navigation.js' %}"></script>
    <script src="{% static 'js/active.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $('#id_project').change(function () {
          var url = "{% url 'ajax_load_contractors' %}";
          var projectId = $(this).val();
        
          $.ajax({
            url: url,
            data: {
              'project': projectId
            },
            success: function (data) {
              $("#id_contractor").html(data);
            }
          });
        });
        </script>
        














   
</body>
</html>